export const ActionTypes = {
  MODAL_OPEN: 'MODAL_OPEN',
  MODAL_CLOSE: 'MODAL_CLOSE',

  HANDLE_OPEN_BURGER_MENU: 'HANDLE_OPEN_BURGER_MENU',
  HANDLE_BURGER_EVENT_BUTTON: 'HANDLE_BURGER_EVENT_BUTTON',

  HANDLE_URL_PAGE : "HANDLE_URL_PAGE",

  HANDLE_TOTAL_PAGE : "HANDLE_TOTAL_PAGE",
};