export const ActionTypes = {
  FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
  FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
  FETCH_USERS_ERROR : 'FETCH_USERS_ERROR',

  FETCH_USER_BY_ID_REQUEST: 'FETCH_USER_BY_ID_REQUEST',
  FETCH_USER_BY_ID_SUCCESS: 'FETCH_USER_BY_ID_SUCCESS',
  FETCH_USER_BY_ID_ERROR: 'FETCH_USER_BY_ID_ERROR',

  ADD_USER_REQUEST : 'ADD_USER_REQUEST',
  ADD_USER_SUCCESS : 'ADD_USER_SUCCESS',
  ADD_USER_ERROR : 'ADD_USER_ERROR',
};